kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: elasticsearch
        image: elasticsearch:5.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 3Gi
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - name: http
    port: 9200
    nodePort: 32686
    protocol: TCP
  - name: transport
    port: 9300
    nodePort: 32687
    protocol: TCP
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: elasticsearch
